# dummy_emu_host
FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && apt-get -y upgrade 
RUN apt install -y iperf3 iproute2 iputils-ping tmux wget git xz-utils sudo keyboard-configuration \
build-essential python3-serial socat cmake

RUN pip3 install swifter duckdb pandas numpy --break-system-packages 
RUN git clone https://github.com/qznwpfqbgw/mobileinsight-core.git
RUN cd mobileinsight-core && git checkout ubuntu22_04 && ./install-ubuntu.sh

CMD ['/bin/bash']
